### ISSUE TITLE
[android, device] Application entry point file not found. 

### ISSUE THREAD

**Issue by unit-cesar** [NathanWalker/angular-seed-advanced#481] opened 2018-01-19 16:37 UTC
```
[X] bug report 
```

**Current behavior**
Project without changes, just cloned (git) and installed (`npm install`)
Running in browser perfectly with: `npm run start`
Running in android device, but with errors. _Moto G (2nd generation) - Android 6.0_
![image](https://user-images.githubusercontent.com/11687314/35152592-b9d1402e-fd01-11e7-8ff6-97a6acdcd474.png)

**Minimal reproduction of the problem with instructions**
$ `npm install`
...
$ `npm run start.android.device`
...
![image](https://user-images.githubusercontent.com/11687314/35152832-c719ff90-fd02-11e7-98a2-36db8558f72f.png)
...

> [1] Project successfully built.
> [1] Installing...
> [1] Successfully installed on device with identifier '0016069577'.
> [1] Successfully transferred all files.
> [1] Refreshing application...
> [1] Successfully synced application com.yourdomain.nativescript on device 0016069577.
> [1] Executing before-watch hook from /home/devesa/testes/angular-seed-advanced/nativescript/hooks/before-watch/nativescript-dev-sass.js
> [1] Found peer node-sass
> [1] ActivityManager: Start proc 5215:com.yourdomain.nativescript/u0a135 for activity com.yourdomain.nativescript/com.tns.NativeScriptActivity
> [1] System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
> [1] System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
> [1] System.err: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
> [1] System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
> [1] System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> [1] System.err: 	at android.os.Looper.loop(Looper.java:148)
> [1] System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
> [1] System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> [1] System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
> [1] System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
> [1] System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
> [1] System.err: 	at com.tns.Module.bootstrapApp(Module.java:311)
> [1] System.err: 	at com.tns.Runtime.run(Runtime.java:512)
> [1] System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
> [1] System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
> [1] System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
> [1] System.err: 	... 8 more
> [1] System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
> [1] System.err: 	at com.tns.Module.resolvePathHelper(Module.java:146)
> [1] System.err: 	at com.tns.Module.bootstrapApp(Module.java:309)
> [1] System.err: 	... 12 more
> [1] ActivityManager: Process com.yourdomain.nativescript (pid 5215) has died
> 

**I've tried all this, but nothing changes:**
I deleted the directories: (app - platforms - hooks - node_modules) and unistall app in device.
I tried `npm run reinstall -f`
I tried `npm rebuild node-sass -f`
I tried follow steps to 'Prevent Permissions Errors' (https://docs.npmjs.com/getting-started/fixing-npm-permissions)
I tried re-cloned
I tried reinstall Angular, TypeScript, NativeScript
I tried update angular/cli (_1.6.4_ to _1.6.5_)
I tried downgrade Node.js Latest to LTS (_v9.4.0_ to _v8.9.4_)
I tried `tns doctor` and ok (No issues were detected.)
I tried HelloWold of NativeScript tutorial and ok, normally runs on the device:
> $ `tns create HelloWorld --template nativescript-template-ng-tutorial`
> $ `cd HelloWorld/`
> $ `tns run android`

_

**About my environment:**
OS: Linux x64 - Ubuntu 17.10
IDE: Sublime Text / PhpStorm
_But I'm only using the Terminal in this case!_

* **Angular Seed Version:** 
`git rev-parse origin/master`
2d652e157a4841830f616fbc9be69d8fddf2ae2e

* **Node:** 
`node --version` 
v9.4.0

* **NPM:** 
`npm -v`
5.6.0

![image](https://user-images.githubusercontent.com/11687314/35154927-d075c5a8-fd0a-11e7-9908-0460c6d649a2.png)

**Comment by mozi22** [comment] 2018-02-05 17:05
did you manage to fix it ?

**Comment by unit-cesar** [comment] 2018-02-05 19:27
Not yet! But I'll check for NPM packets updates and I'll try again soon!

**Comment by josephhsieh** [comment] 2018-02-12 03:04
I got same error.

**Comment by prashanthglen** [comment] 2018-03-14 15:45
I too am getting the same error

**Comment by mozi22** [comment] 2018-04-04 09:50
You can resolve this error by simply changing your `browser-sync` version. In your root `package.json`. 

Change 

` "@types/browser-sync": "^0.0.34",`

To

` "@types/browser-sync": "^0.0.38",`

**Comment by MTomaselloRise** [comment] 2018-05-14 14:04
@mozi22 's answer fixed the problem for me. Thank you so much!

**Comment by thomaspetrou** [comment] 2018-07-12 13:30
Hello all,

Same error as far as i can see which is not fixed by the above fix.
Please note that i am also getting the following compilation errors.

**Exception**
`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:311)
	at com.tns.Runtime.run(Runtime.java:512)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	... 8 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:146)
	at com.tns.Module.bootstrapApp(Module.java:309)
	... 12 more
`

**Compilation errors**
`[0] ./node_modules/@types/fs-extra/index.d.ts(210,86): error TS2694: Namespace '"fs"' has no exported member 'symlink'.
[0] ./node_modules/@types/fs-extra/index.d.ts(212,87): error TS2694: Namespace '"fs"' has no exported member 'symlink'.
[0] ./node_modules/@types/fs-extra/index.d.ts(210,86): error TS2694: Namespace '"fs"' has no exported member 'symlink'.
[0] ./node_modules/@types/fs-extra/index.d.ts(212,87): error TS2694: Namespace '"fs"' has no exported member 'symlink'.
[0] [16:22:56] TypeScript: 2 semantic errors
[0] [16:22:56] TypeScript: 2 emit errors
[0] [16:22:56] TypeScript: emit failed
`

notes:
1. npm --version -> 6.1.0
2. node --version -> v10.6.0
3. tns --version -> 4.1.2
4. Windows and Web run without any problem
5. running ubuntu v18.04
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

Any ideas?
Thanks!

**Comment by thomaspetrou** [comment] 2018-07-13 06:16
Dear all, strange  by good news :)!!!

I have re-downloaded the source code, i made the changed to "@types/browser-sync": "^0.0.38", and it now works!.

Please note that before re-downloading the code i tried to troubleshoot and noticed that fs-extra's (the plugin reporting errors) git repository was giving a message that "you can not download the latest version at this point". Although angular-seed-advanced is not using the latest version of fs-extra  I guess something was going on with the downloading of the plugins during installation.

Other explanations are welcome and possibly more accurate than this :)



Thanks
Thomas

**Comment by jirimracek** [comment] 2018-12-22 18:31
I fell into the same trap.  
Once you make the change you need to run npm install again.  Or start from scratch

**Comment by Geeta-Singh** [comment] 2019-05-05 09:14
I'm also getting same issues with "@types/browser-sync": "^0.0.43",

**Comment by PiyushHM** [comment] 2020-12-17 11:40
I was not using browser-sync. I removed mode_modules and platform folder.

npm install and it worked.

**Closed as completed** 2020-12-17 12:04 UTC
