### ISSUE TITLE
Nativescript build exception

### ISSUE THREAD

**Issue by ottojimb** [NathanWalker/angular-seed-advanced#271] opened 2016-10-14 00:02 UTC
Cloning the repo (or downloading the zip), and following the steps to run the app the first time (npm install, and git setup), when I'm try to running the android emulator o physical device, it's launching a exception:

<img width="663" alt="{N} exception" src="https://cloud.githubusercontent.com/assets/1256428/19371271/61226968-9177-11e6-9394-eb369bb0782b.png">

I'm missing something or it's a bug?

**Comment by chaitanya9186** [comment] 2016-10-14 03:17
I am also getting same exception on Android. 

In iOS Segmentation fault:
 file:///app/app/frameworks/i18n/services/multilingual.service.js:7:30: JS ERROR SyntaxError: Importing binding name 'EventEmitter' is not found.
Oct 13 20:16:59 HOST com.apple.CoreSimulator.SimDevice.5667AD65-6154-405B-A7B8-191473F00F2C.launchd_sim[90443](UIKitApplication:com.yourdomain.appname[0x2e14][4815]): Service exited due to signal: Segmentation fault: 11

**Comment by hypery2k** [comment] 2016-10-14 05:57
duplicate of #270

**Comment by NathanWalker** [comment] 2016-10-14 06:21
@ottojimb please see this comment: https://github.com/NathanWalker/angular-seed-advanced/issues/270#issuecomment-253719072

**Closed as completed by NathanWalker** 2016-10-14 06:21 UTC
