### ISSUE TITLE
Sass/Less/Compass Support?

### ISSUE THREAD

**Issue by syrys** [NathanWalker/angular-seed-advanced#182] opened 2016-07-29 12:01 UTC
Hey Guys,

Im curious, there seems to be some flags within the config files implying sass support, but i cant seem to get it enabled. Does this seed project have sass support out of the box, or would i need to add a new sass/compass/less package and write a gulp task for it manually?

Any help would be appreciated. I prefer to have Compass support.

Cheers

**Comment by syrys** [comment] 2016-07-29 22:31
Actually, i figured out the sass integration my self after looking at the sass branch (didnt see it before). Although, i did have trouble merging that branch with master unfortunately (lot of conflicts, seems to be using a much older version of the repo). I just looked at what they did with the sass branch and made the changes manually (fairly simple, adding/changing about 5 files). 

Maybe someone should consider adding an updated sass branch or integrate sass to master (since sass/less is very common practice for web projects these days) but leave it as a flag that you can turn on/off if you are unsure about users wanting this feature or not. Its just a suggestion.

Cheers.

**Comment by yvoronen** [comment] 2016-07-29 22:48
syrys, we use sass, no problems at all. No need to merge any branches.

Just edit your project config file `tools/config/project.config.ts`, add the following line:

```
 constructor() {
    super();
    this.ENABLE_SCSS = true;   <-- ADD THIS LINE
    this.APP_TITLE = 'My App';
```

FYI, this overrides settings in `seed.config.ts` and `seed-advanced.config.ts`. Don't edit those files directly.

**Comment by syrys** [comment] 2016-07-29 23:38
@yvoronen oh really? I will give that a try soon and get back to you. I guess i have been doing it wrong this whole time haha. I did went ahead and edited the definition of ENABLE_SCSS on the file it was defined (seed.config.ts i believe) to test it and hard coded it to true, but threw some errors when i tried to `npm start` (it was probably getting overwritten maybe). Anyway, i will get back to everyone here after trying what you suggested.

**Comment by syrys** [comment] 2016-07-30 01:21
@yvoronen that worked perfectly. Awesome. I didnt realise that the package.json had sass imported, i would have looked in further if i saw that haha. Derp moment.

Im curious though, if i wanted to change some compile settings for sass (not sure why this is not already there by default), is this the correct way to approach (ofcorse it works fine, just want some input):

`project.config.ts` (inside the constructor after enabling SCSS):

```
this.PLUGIN_CONFIGS['gulp-sass'].outputStyle = this.ENV === ENVIRONMENTS.DEVELOPMENT? 'nested' : 'compressed';
this.PLUGIN_CONFIGS['gulp-sass'].sourceComments = this.ENV === ENVIRONMENTS.DEVELOPMENT? true : false;
```

_obviously import the ENVIRONMENTS from the seed.config at the top._

**Comment by yvoronen** [comment] 2016-07-30 08:38
Glad it helped! This looks right. There is a helper to assist with this:

```
this.mergeObject(this.PLUGIN_CONFIGS['gulp-sass'], { 
    outputStyle: ..., 
    sourceComments: ...
});
```

but you don't have to use it really.

**Comment by syrys** [comment] 2016-07-30 09:35
@yvoronen ah awesome, i will use that for consistency sake (and so i remember that helper exists haha).

All works. Had to do few more tweaks before getting it working though. All was fine for dev build, but the production build failed due to existence of the component css files. Again, only change i have done to the project from master branch by this point is to add the lines mentioned above and deletion of `/css/main.css` and replacing that by `/css/main.scss`. The solution was to go around and rename all the default component css files to scss extension. Maybe this should get doccumented somewhere or someone should look into who enabling scss not play nice with the component css files (maybe its by design). Meh, works fine for me now that i have renamed the files :)

Thanks again for the help, greatly appreciated. Now to figure out electron dependencies and such.

**Comment by syrys** [comment] 2016-07-30 10:17
@yvoronen (or anyone else :p) are you by any chance able to give me some advice on something electron related (maybe i should make a different ticket, but there doesnt seem to be any place i can ask for some support questions and i feel bad asking support queries in issues section). 

Im trying to intergrate the electron's ipc connection with the code (more info here: `https://github.com/electron/electron/blob/master/docs/api/ipc-main.md`). I can easily do the backend part of it (simply adding the IPCMain stuff to the `main.desktop.ts`). But the Angular side of it is a bit confusing and i cannot seem to get this to work. The part im confused by is how to import electron to angular side (lets say the home component) so i get access to the `ipcRenderer` object. Im sure i have to inject electron in somehow before anything (to get the `ipcRenderer` from import statement), but not quite sure how to do this. Can someone enlighten me? Also, given the way the project is structured, how would one go about creating IPC communication given the fact that the project can build to Web as well as Desktop (and IPC only makes sense for desktop builds), is there maybe a conditional import or a conditional component?.

TY in advance

**Comment by m-abs** [comment] 2016-09-27 13:48
Hey,

I'm trying to add sass support to our project, but I can't get the nativescript-part to build the .scss-files.

**_What I've done:**_
- Renamed all .css-files to .scss
- ran `tns install sass`
- set ENABLED_SCSS=true for `tools/config/seed.config.ts` (this is only for web)

`npm run start` works just fine, `scss` is translated into `css`.
`tns livesync android --watch` in the nativescript-folder doesn't work, `scss` is not translated into `css`.

This is caused by the app-symlink and `glob` that `nativescript-dev-sass` uses here: https://github.com/toddanglin/nativescript-dev-sass/blob/master/lib/converter.js#L19

The only solution I've right now is to patch `converter.js`, so it gived the option: 

``` javascript
{
  follow: true
}
```

Do you have a better solution? Or should I submit a patch to `nativescript-dev-sass`?

PS: I'm on Linux.

**Comment by NathanWalker** [comment] 2016-10-17 07:28
@m-abs a patch to the plugin would be nice if you haven't already.

**Comment by m-abs** [comment] 2016-10-17 11:22
@NathanWalker I made a PR for them, https://github.com/toddanglin/nativescript-dev-sass/pull/13 but we're running on my fork (https://github.com/m-abs/nativescript-dev-sass/tree/notalib-fixes) of the plugin because it haven't been merged yet.

**Comment by m-abs** [comment] 2016-10-21 22:09
Isn't this issue resolved? My PR for NativeScript-dev-sass have been merged.

**Comment by NathanWalker** [comment] 2016-10-22 15:46
Yes it is thanks!

**Closed as completed by NathanWalker** 2016-10-22 15:46 UTC

**Comment by symplyscott** [comment] 2016-11-01 16:30
Not sure if this deserves it's own issue or it's just an isolate thing with my project but when I try to enable sass on a project from the seed and I execute `start.deving`, it hangs on the `[09:26:16] Starting 'build.html_css'...` of this.  Commenting the line `this.ENABLE_SCSS = true;` fixes this and it compiles but of course sass is not enabled.
