### ISSUE TITLE
Desktop version doesn't loads

### ISSUE THREAD

**Issue by axinedy** [NathanWalker/angular-seed-advanced#444] opened 2017-06-07 06:43 UTC
Hello. 
Tried this seed:
`git clone https://github.com/NathanWalker/angular-seed-advanced.git`
`cd angular-seed-advanced`
`npm install`
`npm run build.desktop.windows`
`desktop\windows\angular-seed-advanced.exe`
And no application in electron window, only "Loading..."

I've modified src/client/main.desktop.ts, just following line
`  mainWindow.webContents.openDevTools();`

And now we can see following errors in console:
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/core-js/client/shim.min.js?1496815509912 `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/intl/dist/Intl.min.js?1496815509912 `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/systemjs/dist/system.src.js?1496815509928 `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/system-config.js `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/zone.js/dist/zone.js?1496815509928 `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/zone.js/dist/long-stack-trace-zone.js?1496815509928 `
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/node_modules/.tmp/Rx.min.js?1496815509928 `
`Uncaught ReferenceError: System is not defined
index.html:62 `

Though in browser (npm start) it works fine

**Comment by axinedy** [comment] 2017-06-07 06:53
After I've modified desktop/windows/resources/app/index.html
Replaced all "/ to "
`  <script src="/system-config.js"></script>`
became 
`  <script src="system-config.js"></script>` 
and so on.
And I couldn't get a working desktop version again. Now it has following errors:
`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/main.web.js `
`(SystemJS) XHR error loading file:///C:/main.web.js index.html:64`
`	Error: XHR error loading file:///C:/main.web.js `
`	    at ZoneDelegate.invokeTask (file:///C:/angular-seed-advanced/desktop/windows/resources/app/node_modules/zone.js/dist/zone.js?1496815509928:414:31)`
`	    at Zone.runTask (file:///C:/angular-seed-advanced/desktop/windows/resources/app/node_modules/zone.js/dist/zone.js?1496815509928:181:47)`
`	    at XMLHttpRequest.ZoneTask.invoke (file:///C:/angular-seed-advanced/desktop/windows/resources/app/node_modules/zone.js/dist/zone.js?1496815509928:476:38)`
`	Error loading file:///C:/main.web.js Not expecting this error? Report it at https://github.com/NathanWalker/angular-seed-advanced/issues`

**Comment by 730alchemy** [comment] 2017-06-11 06:00
For an explanation of the cause of this problem, take a look at the pull request named "Issue.444"

**Comment by NathanWalker** [comment] 2017-07-09 00:21
Closed by https://github.com/NathanWalker/angular-seed-advanced/pull/447

**Closed as completed by NathanWalker** 2017-07-09 00:21 UTC
