### ISSUE TITLE
NativeScript and Array.find() error

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#244] opened 2016-09-22 20:33 UTC
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

if you use array.find() in your code, something like:

```
   let  foo:Array<any> = ['foo', 'bar'];
   let bar = foo.find((item, index, obj) => { return item === 'bar'; })
```

It works fine for web/desktop, but when building for {N} you get this error with TypeScript 1.8.10: `error TS2339: Property 'find' does not exist on type 'any[]'`!!

googling did not get me anything useful, or a hint at how to solve it.

I also looked at the tsconfig file in nativescript and compared it to the one in the root, but did not spot any meaningful difference. I even tried to use the exact same compiler options but got the same error.

One of the suggestions in stackoverflow was to change the compile target to "ES6", but of course that does not work for {N} (in fact that produces a whole new set of errors in {n} code). But it does get rid of the `array.find()` errors :-(

Does anyone have any other hint at a solution/fix?

TIA

**Comment by m-abs** [comment] 2016-10-02 19:45
It's an typing issue caused by the typing from `nativescript`.

We've solved it by adding the typing to our `nativescript/references.d.ts`:

``` typescript
declare interface Array<T> {
  find(predicate: (element: T, index?: number, array?: Array<T>) => boolean): T;
  findIndex(predicate: (element: T, index?: number, array?: Array<T>) => boolean): number;
}
```

**Comment by NathanWalker** [comment] 2016-10-17 04:03
The above is a good fix for this, thanks @m-abs :)

**Closed as completed by NathanWalker** 2016-10-17 04:03 UTC
