### ISSUE TITLE
Error NativeScriptFormsModule import in browser

### ISSUE THREAD

**Issue by michaelAntony** [NathanWalker/angular-seed-advanced#365] opened 2017-02-22 10:05 UTC
ngModel is working fine inside nativescript's component's ts file, but its not working inside nativescript's shared folder's ts file(nativescript->shared->sample->components). I imported NativeScriptFormModule from nativescript-angular/forms in sample.module.ts file and worked in iOS. But running in browser shows cant find module nativescript-angular/forms. How can i solve this?

**Comment by psmontte** [comment] 2017-02-23 19:02
Please submit issue in the prescribed format.

**Comment by sanderbos1402** [comment] 2017-03-02 22:33
the issue is that you need to import either the "normal" formsmodule or the nativescript formsmodule.
declaring a component outside the app folder enabled you to change the implementation based on platform. For the web this implementation is in ./src. `for nativescript this is in ./nativescript/src/

I called it platform.module

if you import this in the sample module (or any other module) this will import the correct forms module. If needed this can of course also be done for other modules.  
see pull request #370. you can see the changes I made. This works for me, I hope it also works for you, let me know please.

**Comment by NathanWalker** [comment] 2017-04-20 18:43
Thank you @sanderbos1402 anyone coming across can implement his suggestions in that PR.
The PR will be merged into master once a couple tweaks are made.

**Closed as completed by NathanWalker** 2017-04-20 18:43 UTC
